### ISSUE TITLE
Do not abort if dependency has no license file

### ISSUE THREAD

**Issue by hschendel** [Coronon/license_gatherer#1]
Hello Rubin,

thank you for this nice tool which is very helpful in extracting the dependency licenses from a Dart project, and saved me a lot of work 😄 

I have a small improvement idea: Sometimes dependencies do not have a license (e.g. the "builtin" flutter_localizations) which results in the license_gatherer to simply abort with an error, as implemented here: 
https://github.com/Coronon/license_gatherer/blob/47c3db46d957ac8bc4a3705a3362c00ee53f16c7/lib/src/gather_licenses.dart#L30

In my opinion, it would be sufficient to report the fact that a dependency does not have a license to stderr or so, and continue writing the NOTICE file.

What do you think?

Thank you!
-Hagen

**Comment by Coronon** [comment]
Moin Hagen,

that sounds reasonable - we could add a '_--strict_' option to still fail when not all dependencies can be resolved.

I also wanted to add custom formats and an easier to use cli, so it might be time for a new version. Could you provide a _pubspec_ that reproduces this problem?

Greetings
Rubin

**Edit**: will probably look into this on Wednesday

**Comment by Coronon** [comment]
Ok, just added a bunch of new features! Have a look at [the changelog](https://github.com/Coronon/license_gatherer/blob/master/CHANGELOG.md#110).

The major new features are:
- ability to specify custom format
- unified logging
- pedantic mode

Hope this helps you. If you are satisfied, I will push this new version to pub tomorrow :)

**Comment by Coronon** [comment]
Changes have been [published to pub.dev](https://pub.dev/packages/license_gatherer/changelog#110).

**Comment by hschendel** [comment]
Hello Rubin,

sorry for taking so long to answer here.
Your new release works fine for me :) Thank you!

Btw, if you want to see what triggers the error, just look at this: https://docs.flutter.dev/development/accessibility-and-localization/internationalization#setting-up
